server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa

  sql:
    init:
      mode: always
      encoding: utf-8
      schema-locations: classpath*:db_schema.sql

logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG

# aws s3
cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: btrips

fcm:
  key:
    path : btrips-db903-firebase-adminsdk-nhhz4-6a279ab0e3.json